server:
  port: 8104

spring:
  application:
    name: dubbo-business-example
#====================================Dubbo config===============================================
dubbo:
  application:
    id: dubbo-business-example
    name: dubbo-business-example
    qosEnable: false
    metadata-type: remote
  protocol:
    id: dubbo
    name: dubbo
    port: 10001
  registry:
    id: dubbo-business-example-registry
    address: nacos://127.0.0.1:8848
  config-center:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848
  consumer:
    timeout: 600000
    retries: 0
    provided-by: dubbo-account-example,dubbo-order-example,dubbo-storage-example
#====================================Seata Config===============================================
seata:
  enabled: true
  application-id: business-seata-example
  tx-service-group: business-service-seata-service-group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      cluster: default
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      namespace: ""
      server-addr: localhost:8848
      group: SEATA_GROUP